[platformio]
name = abracadabra-platformio

[env:xiaoblesense_arduinocore_mbed]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoblesense
framework = arduino
monitor_speed = 115200
upload_protocol = nrfutil
lib_deps =
	seeed-studio/Seeed Arduino LSM6DS3@2.0.4
	bblanchon/ArduinoJson@7.4.3
	arduino-libraries/ArduinoBLE@2.0.1
